# Generated by Django 3.2.10 on 2022-09-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user', models.BooleanField(default=False, verbose_name='Is user')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Is moderator')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin')),
            ],
        ),
        migrations.RenameField(
            model_name='script',
            old_name='user',
            new_name='content',
        ),
        migrations.AddField(
            model_name='script',
            name='is_patched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.CharField(default='20220906191032', max_length=200, primary_key=True, serialize=False),
        ),
    ]
