# Generated by Django 3.2.10 on 2022-09-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_script_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20220918193342', max_length=200, primary_key=True, serialize=False),
        ),
    ]
