# Generated by Django 3.2.10 on 2022-09-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20220906_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.CharField(default='20220906191720', max_length=200, primary_key=True, serialize=False),
        ),
    ]
