# Generated by Django 3.2.7 on 2022-09-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.CharField(default='20220906205207', max_length=200, primary_key=True, serialize=False),
        ),
    ]
