# Generated by Django 3.2.7 on 2022-09-08 06:35

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20220908_0509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('User.user',),
            managers=[
                ('moderator', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('User.user',),
            managers=[
                ('normalUser', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.CharField(default='20220908113541', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20220908113541', max_length=200, primary_key=True, serialize=False),
        ),
    ]
