# Generated by Django 3.2.10 on 2022-09-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20220924_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20220924113335', max_length=200, primary_key=True, serialize=False),
        ),
    ]
