# Generated by Django 3.2.7 on 2022-09-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20220906_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.CharField(default='20220906215017', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20220906215017', max_length=200, primary_key=True, serialize=False),
        ),
    ]
