# Generated by Django 3.2.7 on 2022-09-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20220908_0509'),
        ('User', '0007_alter_script_id'),
    ]

    operations = [
    ]
