# Generated by Django 3.2.7 on 2022-09-08 08:23

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20220908_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatekey',
            name='jason',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.CharField(default='20220908132321', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20220908132321', max_length=200, primary_key=True, serialize=False),
        ),
    ]
