# Generated by Django 3.2.7 on 2022-09-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20220908_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatekey',
            name='jason',
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.CharField(default='20220908135539', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20220908135539', max_length=200, primary_key=True, serialize=False),
        ),
    ]
