# Generated by Django 3.2.7 on 2022-10-01 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_script_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20221001170443', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='LikeCommentCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
