# Generated by Django 3.2.10 on 2022-09-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20220910_0749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moderator',
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.CharField(default='20220910075215', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20220910075215', max_length=200, primary_key=True, serialize=False),
        ),
    ]
