# Generated by Django 3.2.7 on 2022-09-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20220907_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatekey',
            name='script',
        ),
        migrations.AddField(
            model_name='privatekey',
            name='script_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.CharField(default='20220907211931', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='privatekey',
            name='privateKey',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20220907211931', max_length=200, primary_key=True, serialize=False),
        ),
    ]
