# Generated by Django 3.2.7 on 2022-10-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20221008_1533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DraftContent',
            new_name='SuspendContent',
        ),
    ]
