# Generated by Django 3.2.7 on 2022-10-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_remove_suspendcontent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_suspend',
            field=models.BooleanField(default=False),
        ),
    ]
