# Generated by Django 3.2.7 on 2022-09-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_auto_20220918_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20220918234930', max_length=200, primary_key=True, serialize=False),
        ),
    ]
