# Generated by Django 3.2.7 on 2022-09-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_alter_script_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20220918235357', max_length=200, primary_key=True, serialize=False),
        ),
    ]
