# Generated by Django 3.2.7 on 2022-09-24 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_script_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.badge')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='SuspendContent',
            new_name='FavContent',
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20220924105041', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
