# Generated by Django 3.2.7 on 2022-09-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_auto_20220924_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20220924105153', max_length=200, primary_key=True, serialize=False),
        ),
    ]
