# Generated by Django 3.2.7 on 2022-09-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_auto_20220924_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20220924120548', max_length=200, primary_key=True, serialize=False),
        ),
    ]
