# Generated by Django 3.2.7 on 2022-09-24 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_auto_20220924_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftcontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.content'),
        ),
        migrations.AlterField(
            model_name='draftcontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20220924125314', max_length=200, primary_key=True, serialize=False),
        ),
    ]
