# Generated by Django 3.2.7 on 2022-09-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_auto_20220924_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(default='20220924125341', max_length=200, primary_key=True, serialize=False),
        ),
    ]
